services:
  db:
    image: postgres:14
    container_name: user_db
    restart: always
    environment:
      POSTGRES_USER: student
      POSTGRES_PASSWORD: verystrongpassword
      POSTGRES_DB: user_service
    ports:
      - "5435:5432"
    volumes:
      - user_db_data:/var/lib/postgresql/data

  user_service:
    build: ./users_service
    container_name: user_service
    restart: always
    depends_on:
      - kafka
      - db
    environment:
      DATABASE_URL: "postgresql://student:verystrongpassword@user_db:5432/user_service"
      JWT_SECRET_KEY: "super-duper-secret-key"
      KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
    ports:
      - "5002:5000"

  posts_db:
    image: postgres:14
    container_name: posts_db
    restart: always
    environment:
      POSTGRES_USER: student
      POSTGRES_PASSWORD: verystrongpassword
      POSTGRES_DB: posts_db
    ports:
      - "5434:5432"
    volumes:
      - posts_db_data:/var/lib/postgresql/data

  posts-service:
    build:
      context: .
      dockerfile: ./posts_service/Dockerfile
    container_name: posts-service
    restart: always
    depends_on:
      - posts_db
    environment:
      DATABASE_URL: "postgresql://student:verystrongpassword@posts_db:5432/posts_db"
      KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
    ports:
      - "50051:50051"

  gateway_service:
    build:
      context: .
      dockerfile: ./gateway/Dockerfile
    container_name: gateway_service
    restart: always
    depends_on:
      - user_service
      - posts-service
    environment:
      USER_SERVICE_URL: "http://user_service:5000"
      POSTS_SERVICE_URL: "posts-service:50051"
      JWT_SECRET_KEY: "super-duper-secret-key"
    ports:
      - "4001:4000"

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    volumes:
      - zookeeper_data:/var/lib/zookeeper

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - kafka_data:/var/lib/kafka/data

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "8080:8080"
    depends_on:
      - kafka
    environment:
      KAFKA_CLUSTERS_0_NAME: "local-kafka"
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: "kafka:9092"
      KAFKA_CLUSTERS_0_ZOOKEEPER: "zookeeper:2181"

volumes:
  posts_db_data:
  user_db_data:
  kafka_data:
  zookeeper_data: