syntax = "proto3";

package post;

service PostService {
  rpc CreatePost (CreatePostRequest) returns (Post);
  rpc GetPost (GetPostRequest) returns (Post);
  rpc UpdatePost (UpdatePostRequest) returns (Post);
  rpc DeletePost (DeletePostRequest) returns (Empty);
  rpc GetListOfPosts (GetListOfPostsRequest) returns (GetListOfPostsResponse);
  rpc LikePost (LikePostRequest) returns (Empty);
  rpc ViewPost (ViewPostRequest) returns (Empty);
  rpc AddComment (AddCommentRequest) returns (Comment);
  rpc GetComments (GetCommentsRequest) returns (GetCommentsResponse);
}

message Post {
  int64 id = 1;
  string title = 2;
  string description = 3;
  int64 creator_id = 4;
  string created_date = 5;
  string updated_date = 6;
  bool is_private = 7;
  repeated string tags = 8;
}

message CreatePostRequest {
  string title = 1;
  string description = 2;
  int64 creator_id = 3;
  bool is_private = 4;
  repeated string tags = 5;
}

message GetPostRequest {
  int64 post_id = 1;
  int64 creator_id = 2;
}

message UpdatePostRequest {
  int64 id = 1;
  string title = 2;
  int64 creator_id = 3;
  string description = 4;
  bool is_private = 5;
  repeated string tags = 6;
}

message DeletePostRequest {
  int64 post_id = 1;
  int64 creator_id = 2;
}

message GetListOfPostsRequest {
  int32 page = 1;
  int32 page_size = 2;
  int64 creator_id = 3;
}

message GetListOfPostsResponse {
  repeated Post posts = 1;
}

message LikePostRequest {
  int64 user_id = 1;
  int64 post_id = 2;
}

message ViewPostRequest {
  int64 user_id = 1;
  int64 post_id = 2;
}

message AddCommentRequest {
  int64 user_id = 1;
  int64 post_id = 2;
  string comment_text = 3;
}

message GetCommentsRequest {
  int64 post_id = 1;
  int32 page = 2;
  int32 page_size = 3;
}

message GetCommentsResponse {
  repeated Comment comments = 1;
}

message Comment {
  int64 id = 1;
  int64 user_id = 2;
  string comment_text = 3;
  string created_at = 4;
}

message Empty {}